module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        card: "var(--color-card)",
        "card-foreground": "var(--color-card-foreground)",
        popover: "var(--color-popover)",
        "popover-foreground": "var(--color-popover-foreground)",
        primary: "var(--color-primary)",
        "primary-foreground": "var(--color-primary-foreground)",
        secondary: "var(--color-secondary)",
        "secondary-foreground": "var(--color-secondary-foreground)",
        muted: "var(--color-muted)",
        "muted-foreground": "var(--color-muted-foreground)",
        accent: "var(--color-accent)",
        "accent-foreground": "var(--color-accent-foreground)",
        destructive: "var(--color-destructive)",
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        // Sidebar and chart colors
        sidebar: "var(--color-sidebar)",
        "sidebar-foreground": "var(--color-sidebar-foreground)",
        "sidebar-primary": "var(--color-sidebar-primary)",
        "sidebar-primary-foreground": "var(--color-sidebar-primary-foreground)",
        "sidebar-accent": "var(--color-sidebar-accent)",
        "sidebar-accent-foreground": "var(--color-sidebar-accent-foreground)",
        "sidebar-border": "var(--color-sidebar-border)",
        "sidebar-ring": "var(--color-sidebar-ring)",
        "chart-1": "var(--color-chart-1)",
        "chart-2": "var(--color-chart-2)",
        "chart-3": "var(--color-chart-3)",
        "chart-4": "var(--color-chart-4)",
        "chart-5": "var(--color-chart-5)",
        "accent-color": "var(--accent-color)",
        "accent-dark": "var(--accent-dark)",
        "accent-black": "var(--accent-black)",
        "accent-black2": "var(--accent-black2)",
        "accent-light": "var(--accent-light)",
        "accent-orange": "var(--accent-orange)",
        "secondary-color": "var(--secondary-color)",
        "accent-blue": "var(--accent-blue)",
        "disable-color": "var(--disable-color)",
        "border-color-1": "var(--border-color-1)",
        "text-color-1": "var(--text-color-1)",
        "text-color": "var(--text-color)",
        "text-grey": "var(--text-grey)",
        "text-grey2": "var(--text-grey2)",
        "text-grey3": "var(--text-grey3)",
        "text-color-disable": "var(--text-color-disable)",
        "bg-grey": "var(--bg-grey)",
        "grey-light": "var(--grey-light)",
        "border-color": "var(--border-color)",
        "border-color-grey": "var(--border-color-grey)",
        "bg-light": "var(--bg-light)",
        "counter-green": "var(--counter-green)",
        "green-hover": "var(--green-hover)",
        grey7: "var(--grey7)",
      },
      fontFamily: {
        primary: ["Montserrat", "sans-serif"],
        rife: ["Oswald", "sans-serif"],
      },
      boxShadow: {
        default: "var(--box-shadow-default)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
